apiVersion: v2
name: zabbix-realise
description: Umbrella Helm chart for Zabbix monitoring stack with namespace and ingress
type: application
version: 1.0.0
appVersion: "7.0"

dependencies:
  - name: zabbix
    version: "7.0.16"
    repository: "file://./charts/zabbix"